name: Publish Mods

on: pull_request_target

env:
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
      verified: ${{ steps.verify.outputs.verify }}

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        path: repo

    - uses: actions/checkout@v3
      with:
        path: code

    - uses: actions/checkout@v3
      with:
        repository: geode-sdk/index-test
        path: index
        token: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - id: verify
      working-directory: ${{ github.workspace }}/index
      run: python3 ${{ github.workspace }}/code/.github/verify.py $PR_AUTHOR

    - if: ${{ steps.verify.outputs.verify }} == "true"
      id: check
      working-directory: repo
      run: |
        url=`git remote get-url origin`
        branch=`git rev-parse --abbrev-ref HEAD`
        dirs=`ls -1d */`
        cd ../index
        python3 ../code/.github/reset-repo.py $url

        echo "::set-output name=message::$(for i in $dirs; do
          python3 ../code/.github/add-entry.py ../repo/$i $PR_AUTHOR $url/raw/$branch/$i
        done)"

    - if: ${{ steps.verify.outputs.verify }} == "true"
      run: echo ${{ steps.check.outputs.message }}
      #uses: mshick/add-pr-comment@v2
      #with:
      #  message: ${{ steps.check.outputs.check }}
    - name: Commit, push to index
      working-directory: ${{ github.workspace }}/index
      run: |
        git config --local user.email "${{ secrets.GEODE_BOT_EMAIL }}"
        git config --local user.name "GeodeBot"
        git add -A
        git commit -m "Update from $PR_AUTHOR"
        git remote set-url origin "https://GeodeBot:${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}@github.com/geode-sdk/index-test.git"
        git push -u origin main
